#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
ADAPTER_STATE=$(acpi -a | grep -wo "on-line\|off-line")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

URGENT_VALUE=10

if [[ "${ADAPTER_STATE}" = "on-line" ]] && [[ "${BATTERY_STATE}" = "Charging" ]]; then
    if (( ${BATTERY_POWER} >= 95 )); then
        exit 0
    fi
    echo "${BATTERY_POWER}%+"
    echo "${BATTERY_POWER}%+"
    echo "#85BB00"
elif [[ "${ADAPTER_STATE}" = "off-line" ]] && [[ "${BATTERY_STATE}" = "Discharging" ]]; then
    echo "${BATTERY_POWER}%-"
    echo "${BATTERY_POWER}%-"
    echo "#FF0000"
    if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
        exit 33
    fi
fi 

