#!/bin/bash
# Based on https://aur.archlinux.org/packages/playerctl/

INSTANCE="${BLOCK_INSTANCE}"
TITLE_SIZE_LIMIT=25

if [[ "${INSTANCE}" != "" ]]; then
  ARGUMENTS="--player ${INSTANCE}"
fi

#ICON_PLAY="➤"
#ICON_PAUSE="Ⅱ"
#ICON_STOP="≠"
#CUR_ICON=""

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    $(playerctl ${ARGUMENTS} previous)
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
    $(playerctl ${ARGUMENTS} play-pause)
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    $(playerctl ${ARGUMENTS} next)
fi

PLAYER_STATUS=$(playerctl ${ARGUMENTS} status)
INFO_TITLE=$(playerctl ${ARGUMENTS} metadata title | head -c ${TITLE_SIZE_LIMIT})
INFO_ALBUM=$(playerctl ${ARGUMENTS} metadata album)
INFO_ARTIST=$(playerctl ${ARGUMENTS} metadata artist)

## Uncomment for the icon to display
#if [[ "${PLAYER_STATUS}" = "Paused" ]]; then
#  CUR_ICON="${ICON_PAUSE}"
#elif [[ "${PLAYER_STATUS}" = "Playing" ]]; then
#  CUR_ICON="${ICON_PLAY}"
#else
#  CUR_ICON="${ICON_STOP}"
#fi

if [[ "${INFO_TITLE}" != "" ]] && [[ "${INFO_ARTIST}" != "" ]]; then
  #echo "${INFO_ARTIST} - ${INFO_TITLE} ${CUR_ICON}"
  #echo "${INFO_ARTIST} - ${INFO_TITLE} ${CUR_ICON}"
  echo "${INFO_ARTIST} - ${INFO_TITLE}" 
  echo "${INFO_ARTIST} - ${INFO_TITLE}" 
fi
